---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

I painted her a gushing thing,  
With years about a score;  
I little thought to find they were  
A least a dozen more;  
My fancy gave her eyes of blue,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I've tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

O Oysters, come and walk with us!  
The Walrus did beseech.  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Soft little moon child   
Silver aura of cold   
Mercurial temper   
A sad spirit of old   
Clever little sorceress  
The queen of tides   
Calling forth hurricanes   
As well as lullabies  
Magical medium   
Seeing beyond   
Touching the veil of division   
With a crystal quartz wand  
